apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealed-secrets

bases:
- ../../base

resources:
- namespace.yaml

patchesJson6902:
- target:
    group: security.openshift.io
    version: v1
    kind: SecurityContextConstraints
    name: anyuid
  path: patch-anyuid.yaml